require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PriceQuotesController do

  # This should return the minimal set of attributes required to create a valid
  # PriceQuote. As you add validations to PriceQuote, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all price_quotes as @price_quotes" do
      price_quote = PriceQuote.create! valid_attributes
      get :index
      assigns(:price_quotes).should eq([price_quote])
    end
  end

  describe "GET show" do
    it "assigns the requested price_quote as @price_quote" do
      price_quote = PriceQuote.create! valid_attributes
      get :show, :id => price_quote.id.to_s
      assigns(:price_quote).should eq(price_quote)
    end
  end

  describe "GET new" do
    it "assigns a new price_quote as @price_quote" do
      get :new
      assigns(:price_quote).should be_a_new(PriceQuote)
    end
  end

  describe "GET edit" do
    it "assigns the requested price_quote as @price_quote" do
      price_quote = PriceQuote.create! valid_attributes
      get :edit, :id => price_quote.id.to_s
      assigns(:price_quote).should eq(price_quote)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PriceQuote" do
        expect {
          post :create, :price_quote => valid_attributes
        }.to change(PriceQuote, :count).by(1)
      end

      it "assigns a newly created price_quote as @price_quote" do
        post :create, :price_quote => valid_attributes
        assigns(:price_quote).should be_a(PriceQuote)
        assigns(:price_quote).should be_persisted
      end

      it "redirects to the created price_quote" do
        post :create, :price_quote => valid_attributes
        response.should redirect_to(PriceQuote.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved price_quote as @price_quote" do
        # Trigger the behavior that occurs when invalid params are submitted
        PriceQuote.any_instance.stub(:save).and_return(false)
        post :create, :price_quote => {}
        assigns(:price_quote).should be_a_new(PriceQuote)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PriceQuote.any_instance.stub(:save).and_return(false)
        post :create, :price_quote => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested price_quote" do
        price_quote = PriceQuote.create! valid_attributes
        # Assuming there are no other price_quotes in the database, this
        # specifies that the PriceQuote created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PriceQuote.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => price_quote.id, :price_quote => {'these' => 'params'}
      end

      it "assigns the requested price_quote as @price_quote" do
        price_quote = PriceQuote.create! valid_attributes
        put :update, :id => price_quote.id, :price_quote => valid_attributes
        assigns(:price_quote).should eq(price_quote)
      end

      it "redirects to the price_quote" do
        price_quote = PriceQuote.create! valid_attributes
        put :update, :id => price_quote.id, :price_quote => valid_attributes
        response.should redirect_to(price_quote)
      end
    end

    describe "with invalid params" do
      it "assigns the price_quote as @price_quote" do
        price_quote = PriceQuote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PriceQuote.any_instance.stub(:save).and_return(false)
        put :update, :id => price_quote.id.to_s, :price_quote => {}
        assigns(:price_quote).should eq(price_quote)
      end

      it "re-renders the 'edit' template" do
        price_quote = PriceQuote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PriceQuote.any_instance.stub(:save).and_return(false)
        put :update, :id => price_quote.id.to_s, :price_quote => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested price_quote" do
      price_quote = PriceQuote.create! valid_attributes
      expect {
        delete :destroy, :id => price_quote.id.to_s
      }.to change(PriceQuote, :count).by(-1)
    end

    it "redirects to the price_quotes list" do
      price_quote = PriceQuote.create! valid_attributes
      delete :destroy, :id => price_quote.id.to_s
      response.should redirect_to(price_quotes_url)
    end
  end

end
